### ISSUE TITLE
generate docs via roxygen2

### ISSUE THREAD

**Issue by tdhock** [diego-urgell/BinSeg#1]
hi @diego-urgell please consider using roxygen2 to generate docs.
here is an example of C++ source code with documentation https://github.com/tdhock/FLOPART/blob/main/src/interface.cpp

**Comment by tdhock** [comment]
To generate R/RcppExports.R from `src/*.cpp` files run
```
Rcpp::compileAttributes('path/to/BinSeg')
```

To generate `man/*.Rd` files from `R/*.R` files run
```
devtools::document('path/to/BinSeg')
```

**Comment by diego-urgell** [comment]
Thanks @tdhock, roxygen was very useful for the documentation 🚀
