### ISSUE TITLE
assign new column intead of using cbind

### ISSUE THREAD

**Issue by tdhock** [diego-urgell/BinSeg#16]
hi @diego-urgell can you please change this code in the coef method
```r
     for(j in seq_along(object@param_names)){
       jj <- 6 + (j - 1)*2
       ans <- cbind(ans, build_param(jj, jj+1, curr_segs, object@param_names[j]))
     }
```
to 
```r
set(ans, j=param_name, value=build_param(jj, jj+1, curr_segs, object@param_names[j])))
```
which should be more time/memory efficient.
(your method using cbind involves re-allocating a new data table for every parameter, and this can be avoided)

**Comment by tdhock** [comment]
also would be good to use more informative variable names (single/double letter names like j are potentially confusing)
```r
     for(param_index in seq_along(object@param_names)){
       param_name <- object@param_names[[param_index]]
       other_index <- 6 + (param_index - 1)*2
       set(.....)
     }
```

**Comment by tdhock** [comment]
also when there are magic numbers like "6" in the code it would be good to provide a comment explaining where it comes from. can you please explain? or even better change the code so that it is obvious and comments are no longer needed?
```r
number_of_SOMETHING <- 6
other_index <- number_of_SOMETHING + (param_index - 1)*2
```

**Comment by diego-urgell** [comment]
Thanks @tdhock! It is much better now :)

**Comment by tdhock** [comment]
great
