### ISSUE TITLE
consider loss/algorithm factories instead of if/else blocks

### ISSUE THREAD

**Issue by tdhock** [diego-urgell/BinSeg#3]
hey @diego-urgell I did some reading about the design issues we talked about today.
I found this article which I think would be an alternative (maybe better?) solution to our design issues. https://dzone.com/articles/factory-with-self-registering-types
The analog is ICompressionMethod (that article) ~ loss function or algorithm (our project).
So I think you should consider something like
```c++
class LossFunctionFactory {...};
class LossFunction {...};
class ChangeMeanConstVar :  LossFunction {...};
class ChangeMeanChangeVar :  LossFunction {...};
class AlgorithmFactory {...};
class Algorithm{
  LossFunction loss;
};
class BinarySegmentation : Algorithm {...};
class WildBinarySegmentation : Algorithm {...};
```
This design would achieve the following
- Factory sub-classes which register their name strings to a map for lookup, so that we can avoid a big block of if/else (and avoid separation between algo/loss name strings and functions)
- LossFunction is a member of Algorithm (so loss function methods can be called from within algorithm methods)
does that make sense?

**Comment by diego-urgell** [comment]
Hi @tdhock, @rkillic! I read about the self-registration factories and it was pretty impressive! After careful consideration I decided this was the best approach to follow, it would make it easier to add more algorithms or loss functions in the future. Furthermore, it enforces a better design, based on abstract classes instead of templates for the algorithms/ loss. 

I also created a Registration class so that each Algorithm/loss subclass inherits both from the corresponding abstract class and from Registration, and the code overhead is reduced. Also, as you mention the if block is eliminated.

**Comment by diego-urgell** [comment]
@tdhock, this approach indeed works! I created all the classes and a dummy algorithm that returns a vector of cumsums given an input vector. The result is correct when called from the R interface (I also created a dummy RcppExports function). 

Even tough the algorithm is not implemented yet, this shows that everything runs smoothly and I can proceed with the implementation.

**Comment by rkillick** [comment]
Great, glad to hear that you have tried this and it worked.  It is really encouraging to see you taking feedback on board.

**Comment by tdhock** [comment]
as we discussed yesterday it would be good to avoid repetition such as using a macro/template
```c++
class WildBS: public Algorithm, public Registration<WildBS, Algorithm, AlgorithmFactory>{
```
above WildBS is repeated twice and Algorithm repeated three times, can these be reduced to once each? (simplfy definition of new classes etc) example:
```c++
class WildBS: public Algorithm{
```

**Comment by tdhock** [comment]
this is what I meant when I said you could use macros,
```c++
#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)
#define DISTRIBUTION(SUBCLASS,BODY) class SUBCLASS: public Distribution, public Registration<SUBCLASS, Distribution, DistributionFactory> { \
  public:								\
    inline static std::string factoryName = STRINGIZE(SUBCLASS) ;	\
    SUBCLASS(){is_registered;}						\
    BODY								\
  };

DISTRIBUTION(NormMean, 
 void setCumsum(){
   this -> cumsum = std::make_shared<Cumsum>();
 }
 double costFunction(int start, int end){
   double lSum = this -> cumsum -> getLinearSum(start, end);
   double N = end - start + 1;
   return - pow(lSum, 2)/N;
 }
 )
```
then there is absolutely no repetition in the definition of a new distribution. @diego-urgell can you please try this approach when you implement the other distributions? see https://stackoverflow.com/questions/240353/convert-a-preprocessor-token-to-a-string for a discussion of the "double expansion" trick.

**Comment by diego-urgell** [comment]
This is excellent @tdhock! Thank you! The boilerplate code was completely eliminated, not only in Distributions.cpp but also in Algorithms.cpp

In this commit I also added comments on most functions and classes in order to have a clear picture of the code structure.

**Comment by tdhock** [comment]
Great, I'm glad that works. Can you please edit the macros / classes to support description strings as well? for example
```c
ALGORITHM(BS, "Classic greedy binary segmentation algorithm, always chooses a split that minimizes the cost, over all possible splits given the previously chosen changepoints", 
  etc
)
```
then please store that in a `inline static std::string description` that we can make available to package users so they can find out what each abbreviation means.

**Comment by tdhock** [comment]
this seems to be done
