### ISSUE TITLE
class names consistent with changepoint package

### ISSUE THREAD

**Issue by tdhock** [diego-urgell/BinSeg#5]
to avoid any confusion I think it would be helpful to use the same names for our distribution classes as in
https://github.com/rkillick/changepoint/blob/master/src/cost_general_functions.c
@diego-urgell that would mean for example using `mean_norm` instead of `MeanNorm` -- does that make sense to you?

**Comment by diego-urgell** [comment]
Most of the times I use to name my classes and functions using camelCase, but I realize that in this case it is better to use a notation that is more consistent with the existing R changepoint analysis packages.

**Comment by tdhock** [comment]
great
