### ISSUE TITLE
R functions for querying algorithm / distribution names and descriptions

### ISSUE THREAD

**Issue by tdhock** [diego-urgell/BinSeg#6]
hi @diego-urgell it would be useful to have an R function that the user can run to see what algorithms and distributions are available. (basically, iterate through the map and return a data frame with one row for each subclass, and two columns, name,description)

**Comment by diego-urgell** [comment]
Yes @tdhock, that would be great! I will implement this later on :)

**Comment by diego-urgell** [comment]
Already implemented 😄
